#!/usr/bin/env python3
"""results/coverage.md and coverage.json: Stage-1 obligation -> harness entries -> verdicts -> bounds.

Built from every entry of harnesses.json (not only those with a result) and results/summary.json:
  holds               every entry has a result, all gave their expected verdict, a property entry exists
  refuted-as-expected same, and an RSKIP-reading entry FAILS as expected while Java's behaviour holds
  check               some entry gave an unexpected verdict (incl. TIMEOUT / memory stops: not verdicts)
  pending             no unexpected verdict yet, but some entries have no result
  missing             no harness entry for the obligation
Run by run-jbmc.sh after every run; run it directly after merging a batch.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))


def write(here=HERE):
    obs = [o for o in json.load(open(os.path.join(here, "..", "spec", "obligations.json")))["obligations"] if o["stage"] == 1]
    entries = json.load(open(os.path.join(here, "harnesses.json")))["harnesses"]
    p = os.path.join(here, "results", "summary.json")
    res = {r["id"]: r for r in json.load(open(p))["results"]} if os.path.exists(p) else {}
    by = {}
    for e in entries:
        for o in e.get("obligations", []):
            by.setdefault(o, []).append(e)
    rows, cov = [], []
    for o in obs:
        es = by.get(o["id"], [])
        rs = [res[e["id"]] for e in es if e["id"] in res]
        pend = [e["id"] for e in es if e["id"] not in res]
        roles = {e.get("role", "property") for e in es}
        bad = [r for r in rs if not r["pass"] or r.get("stub_audit") != "none on property path"]
        scope_gaps = sorted({e.get("split_of") for e in es} & {"node-format-3", "store-saved-entries"})
        if not es:
            status = "missing"
        elif bad:
            status = "check"
        elif pend:
            status = "pending"
        elif scope_gaps or "property" not in roles or "negative-control" not in roles:
            status = "check"
        else:
            status = "refuted-as-expected" if "rskip-reading" in roles else "holds"
        # split parts are summarised per base check so the table stays readable
        groups = {}
        for e in es:
            g = e.get("split_of", e["id"])
            r = res.get(e["id"])
            s = groups.setdefault(g, {"role": e.get("role", "property"), "n": 0, "done": 0, "ok": 0, "verdicts": set()})
            s["n"] += 1
            if r:
                s["done"] += 1
                s["ok"] += r["pass"]
                s["verdicts"].add(r["verdict"])
        cell = "; ".join("%s (%s, %s)" % (g, s["role"],
                         ("%s" % "/".join(sorted(s["verdicts"])) if s["n"] == 1 and s["done"] else
                          "%d/%d parts as expected%s" % (s["ok"], s["n"], "" if s["done"] == s["n"] else ", %d without result" % (s["n"] - s["done"]))
                          if s["n"] > 1 else "no result"))
                         for g, s in groups.items())
        bounds = "; ".join(sorted({json.dumps(r["bounds"].get("keys") or r["bounds"].get("note") or
                                              {k: v for k, v in r["bounds"].items() if k not in ("unwind", "flags", "unwindset", "split")},
                                              separators=(",", ":")) for r in rs if r["role"] == "property"}))
        cov.append({"obligation": o["id"], "reading": o["java"]["reading"], "status": status, "pending": pend,
                    "scope_gaps": scope_gaps, "review": [r["id"] for r in bad],
                    "entries": [{"id": r["id"], "role": r["role"], "verdict": r["verdict"], "pass": r["pass"],
                                 "time_s": r["time_s"], "host": r.get("host"), "bounds": r["bounds"]} for r in rs]})
        rows.append("| %s | %s | %s | %s | %s |" % (o["id"], o["java"]["reading"], status, cell, bounds))
    json.dump(cov, open(os.path.join(here, "results", "coverage.json"), "w"), indent=1)
    open(os.path.join(here, "results", "coverage.md"), "w").write(
        "# JBMC coverage of the Stage-1 obligations (generated by coverage.py)\n\n"
        "status: holds = every declared entry has an expected result, stub audits pass, property and negative-control harnesses exist, and no tracked domain gap remains; "
        "refuted-as-expected = additionally the RSKIP reading FAILS as expected while Java's behaviour holds; "
        "check = unexpected verdict, unaudited stub, missing control or tracked domain gap (a time or memory stop is not a verdict); "
        "pending = no unexpected verdict yet but some entries have no result; missing = no entry.\n\n"
        "Six split sentinels have no legal pair and are not extra tested cases. The format3 harness omits third-key deletion; "
        "three savedEntries cases overwrite the first key. See [scope reconciliation](../audits/coverage-reconciliation.md) "
        "for corrections queued after live batches settle. Findings do not imply exhaustive input coverage.\n\n"
        "| obligation | java reading (spec) | status | entries (role, verdict) | property bounds |\n|---|---|---|---|---|\n"
        + "\n".join(rows) + "\n")
    from collections import Counter
    return Counter(c["status"] for c in cov)


if __name__ == "__main__":
    print(dict(write()))
