#!/usr/bin/env python3
"""Merges a second executor's batch results into results/summary.json, keeping host provenance.

    verification/trie/jbmc/merge-batch.py ~/trie-batches/BATCH_ID

A batch counts only if every id in validation.txt has, in the batch's summary.json, the same verdict
and pass value as the local summary.json (the originating host's). Otherwise nothing is merged and
the exit code is 1. Merged work-list results keep their own "host", gain "batch", and their logs and stub
lists go to results/hosts/<host>/. results/coverage.* is regenerated by the next run-jbmc.sh. Run it
while no local run-jbmc.sh is active (that one rewrites summary.json from its own start-time copy).
"""
import json, os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
batch = os.path.abspath(sys.argv[1])
local_path = os.path.join(HERE, "results", "summary.json")
local = json.load(open(local_path))
remote = json.load(open(os.path.join(batch, "results", "summary.json")))
L = {r["id"]: r for r in local["results"]}
R = {r["id"]: r for r in remote["results"]}

bad = []
for i in open(os.path.join(batch, "validation.txt")).read().split():
    l, r = L.get(i), R.get(i)
    if not l or not r or (l["verdict"], l["pass"]) != (r["verdict"], r["pass"]):
        bad.append("%s local=%s remote=%s" % (i, l and (l["verdict"], l["pass"]), r and (r["verdict"], r["pass"])))
if bad:
    sys.exit("validation mismatch, nothing merged:\n  " + "\n  ".join(bad))

bid = os.path.basename(batch)
merged = []
work = os.path.join(batch, "work.txt")
for i in open(work if os.path.exists(work) else os.path.join(batch, "heavy.txt")).read().split():
    r = R.get(i)
    if not r:
        continue
    dst = os.path.join(HERE, "results", "hosts", r["host"])
    os.makedirs(dst, exist_ok=True)
    for ext in (".log", ".stubs.txt"):
        src = os.path.join(batch, "results", i + ext)
        if os.path.exists(src):
            shutil.copy(src, dst)
    r["batch"] = bid
    L[i] = r
    merged.append("%-44s %-15s %s %s" % (i, r["verdict"], "PASS" if r["pass"] else "FAIL", r["host"]))

order = [e["id"] for e in json.load(open(os.path.join(HERE, "harnesses.json")))["harnesses"]]
local["results"] = [L[i] for i in order if i in L]
local["all_pass"] = all(r["pass"] for r in local["results"])
tmp = local_path + ".tmp"
json.dump(local, open(tmp, "w"), indent=2)
os.replace(tmp, local_path)
print("\n".join(merged))
print("merged %d results from %s (validation matched)" % (len(merged), bid))
