#!/usr/bin/env python3
"""jbmc/REPORT.md: the JBMC report, generated from harnesses.json, results/summary.json, the coverage
table and spec/obligations.json, so it can be regenerated after every run or batch merge."""
import json, os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
TRIE = os.path.dirname(HERE)

# Findings: obligations whose RSKIP reading JBMC refutes on the real classes. The severity is this
# report's classification by the rubric printed with the table, not a security assessment.
SEVERITY = {
    # parser accepts non-canonical input, or an integrity property depends on state
    "TRIE-PATH-04": "Medium", "TRIE-LSH-06": "Medium", "TRIE-VARINT-03": "Medium", "TRIE-EMB-02": "Medium",
    "TRIE-NODE-02": "Medium", "TRIE-SER-03": "Medium", "TRIE-SIZE-03": "Medium", "TRIE-VAL-05": "Medium",
    "TRIE-VAL-06": "Medium", "TRIE-HASH-04": "Medium", "TRIE-STORE-06": "Medium",
    "TRIE-HASH-05": "Medium",  # Orchid hash cache ignores the secure flag; latent (callers pass false)
    # fixed, deterministic behaviour that differs from the RSKIP text
    "TRIE-KEY-05": "Low", "TRIE-KEY-10": "Low", "TRIE-EMB-03": "Low", "TRIE-NODE-04": "Low",
    "TRIE-NODE-07": "Low", "TRIE-NODE-08": "Low", "TRIE-STORE-02": "Low", "TRIE-OPS-09": "Low",
    # RSKIP silent or ambiguous; Java implements one reading
    "TRIE-KEY-02": "Info", "TRIE-KEY-07": "Info", "TRIE-PATH-01": "Info", "TRIE-PATH-02": "Info",
    "TRIE-LSH-03": "Info", "TRIE-HASH-02": "Info", "TRIE-SER-05": "Info", "TRIE-SER-08": "Info",
}
RUBRIC = ("Severity is this report's classification, not a security assessment. Medium: the parser "
          "accepts more than one encoding of the same node, or an integrity property (hash, stored "
          "value, migration) depends on state. Low: the shipped behaviour is fixed and deterministic "
          "but differs from the RSKIP text. Info: the RSKIP is silent or ambiguous and Java implements "
          "one reading.")


def main():
    spec = {o["id"]: o for o in json.load(open(os.path.join(TRIE, "spec", "obligations.json")))["obligations"]}
    H = json.load(open(os.path.join(HERE, "harnesses.json")))["harnesses"]
    R = {r["id"]: r for r in json.load(open(os.path.join(HERE, "results", "summary.json")))["results"]}
    cov = json.load(open(os.path.join(HERE, "results", "coverage.json")))
    st = Counter(c["status"] for c in cov)
    roles = Counter(e.get("role", "property") for e in H)
    done = [R[e["id"]] for e in H if e["id"] in R]
    ok = sum(r["pass"] for r in done)
    hosts = Counter(r.get("host") or "?" for r in done)
    secs = sum(r["time_s"] for r in done)
    unsup = [e["id"] for e in H if e.get("status") == "unsupported"]
    splits = Counter(e["split_of"] for e in H if e.get("split_of"))
    L = []
    w = L.append
    w("# JBMC verification of the Java Unitrie against the RSKIPs")
    w("")
    w("Generated by `jbmc/report.py` from `results/summary.json`; regenerate after every run or batch merge.")
    w("")
    w("## Summary")
    w("")
    w("- Stage-1 obligations: %d. Status: %s." % (len(cov), ", ".join("%s %d" % (k, st[k]) for k in
      ("holds", "refuted-as-expected", "pending", "check", "missing") if st[k])))
    w("- Harness entries: %d (%s). Unsupported: %s." % (len(H), ", ".join("%d %s" % (v, k) for k, v in roles.items()),
      ", ".join(unsup) or "none"))
    w("- Results: %d of %d entries; %d gave their expected verdict, %d did not. Entries without a result "
      "are staged on the second executor or still running." % (len(done), len(H), ok, len(done) - ok))
    w("- JBMC time over the recorded results: %.1f h (%s)." % (secs / 3600, ", ".join("%s %d" % kv for kv in hosts.items())))
    w("- Every property result is bounded (see Bounds); `holds` means no counterexample exists within "
      "those bounds on the real compiled rskj classes, with unwinding assertions proving every loop bound "
      "sufficient. It is not an unbounded proof; the Lean development covers the general case.")
    w("")
    w("## Findings")
    w("")
    w(RUBRIC)
    w("")
    pend_f = [c["obligation"] for c in cov if c["obligation"] in SEVERITY and c["status"] != "refuted-as-expected"]
    w("Findings with a JBMC result are listed; RSKIP readings still without a result: %s." % (", ".join(pend_f) or "none"))
    w("")
    w("| obligation | severity | finding | RSKIP | Java | JBMC evidence | reproducer |")
    w("|---|---|---|---|---|---|---|")
    for c in cov:
        if c["status"] != "refuted-as-expected":
            continue
        o = spec[c["obligation"]]
        ev = "; ".join("`%s` %s" % (x["id"], x["verdict"]) for x in c["entries"] if x["role"] in ("rskip-reading", "property"))
        w("| %s | %s | %s | `%s:%s` | %s | %s (%s) | [%s](reproducers/%s.md) |" % (
            c["obligation"], SEVERITY.get(c["obligation"], "?"), o["title"], o["file"], o["lines"],
            "<br>".join("`%s`" % r.replace("rskj-core/src/main/java/", "") for r in o["java"]["refs"][:3]),
            ev, c["status"], c["obligation"], c["obligation"]))
    w("")
    w("## Coverage")
    w("")
    w("Per-obligation entries, verdicts and bounds: [results/coverage.md](results/coverage.md). Status "
      "meanings are given there; a time or memory stop is never counted as a verdict.")
    w("")
    w("| obligation | reading (spec) | status | entries with a result / all |")
    w("|---|---|---|---|")
    for c in cov:
        n = len(c["entries"]) + len(c.get("pending", []))
        w("| %s | %s | %s | %d / %d |" % (c["obligation"], c["reading"], c["status"], len(c["entries"]), n))
    w("")
    w("## Method")
    w("")
    w("- Real classes: JBMC 6.11.0 runs the compiled `rskj-core` classes and their jars at the pinned "
      "commit. No `co.rsk.trie.*`, `TrieKeyMapper`, `Uint8/16/24` or `VarInt` class is stubbed or "
      "re-implemented. Environment models (`models/`) replace only JDK and library code JBMC cannot "
      "execute; each states why it cannot change trie behaviour, and `models-test/` compares them with "
      "the real JDK classes.")
    w("- Keccak-256 is an ideal collision-free oracle (`models/src/org/ethereum/crypto/Keccak256Helper.java`); "
      "properties about concrete digest values are left to the differential tests.")
    w("- Every property harness has a negative control that must fail on its own assertion; every "
      "RSKIP reading is a separate harness expected to fail, with a reproducer.")
    w("- Stubs JBMC substitutes for bodiless methods are listed per result and audited against "
      "`models/benign-stubs.json` (`reaudit.py`; conditional entries are checked in each result's log).")
    w("- Heavy checks are split into parts whose union is the original check (`gen-splits.py`, %s)." %
      ", ".join("%s %d" % kv for kv in splits.most_common()))
    w("- Runs go through `heavy_run.py` (shared lock, memory watchdog, admission and timeout); each run "
      "writes `results/invocation-manifest.json` (argv, classpath and source digests, versions) so a "
      "second executor's results are merged only when its invocation is identical (`merge-batch.py`).")
    w("")
    w("## Bounds and narrowings")
    w("")
    w("Bounds are recorded per entry in `harnesses.json` and `results/summary.json` (`bounds`, `note`). "
      "Narrowings made to fit the time limit, each with its justification:")
    w("")
    for e in H:
        n = (e.get("note") or "") + " " + json.dumps(e.get("bounds", {}))
        if "Narrowed" in n or "fixed" in n and e.get("role") == "property" and not e.get("split_of"):
            w("- `%s`: %s" % (e["id"], e.get("note") or json.dumps(e.get("bounds"))))
    w("- Key universe: multi-key trie harnesses enumerate the 12 keys of `Nondet.KEYS` with symbolic values "
      "of fixed lengths (1, 32, 33 bytes); key harnesses use symbolic 20-byte addresses and 32-byte words "
      "by leading-zero class.")
    w("- `--max-field-sensitivity-array-size 512` on the serialisation-heavy trie parts only affects the "
      "precision of symbolic execution (no semantic change).")
    w("")
    w("## Open items")
    w("")
    pend = [c["obligation"] for c in cov if c["status"] == "pending"]
    w("- Obligations pending results: %s." % (", ".join(pend) or "none"))
    w("- Not run in JBMC (Stage 2): the 3 Stage-2 obligations are out of scope.")
    w("")
    w("## Reproduce")
    w("")
    w("```\n. verification/trie/env.sh\nverification/trie/jbmc/run-jbmc.sh            # every entry\n"
      "verification/trie/jbmc/run-jbmc.sh ID [ID...]   # selected entries\npython3 verification/trie/jbmc/report.py\n```")
    w("")
    open(os.path.join(HERE, "REPORT.md"), "w").write("\n".join(L))
    print("REPORT.md: %d obligations, %s" % (len(cov), dict(st)))


if __name__ == "__main__":
    main()
