import RskjTrie.Obligations.Key
import RskjTrie.Obligations.Path
import RskjTrie.Obligations.Lsh
import RskjTrie.Obligations.Node
import RskjTrie.Obligations.Emb
import RskjTrie.Obligations.Ops
import RskjTrie.Obligations.Hash
import RskjTrie.Obligations.Ser
import RskjTrie.Obligations.Size
import RskjTrie.Obligations.Store
/-!
# RSKIP obligations (verification/trie/spec/obligations.json, Stage 1)

One theorem `RskjTrie.Obligations.trie_<area>_<nn>` per obligation; for diverging items also
`trie_<area>_<nn>_rskip_counterexample`. `lean/obligations-map.json` (generated by
`scripts/gen_map.py`) lists every theorem with its file, line, hypotheses and `#print axioms`.

| file | areas |
|---|---|
| `Obligations/Key.lean` | KEY |
| `Obligations/Path.lean` | PATH |
| `Obligations/Lsh.lean` | LSH, VARINT |
| `Obligations/Node.lean` | NODE |
| `Obligations/Emb.lean` | EMB, VAL |
| `Obligations/Ops.lean` | OPS, CMP |
| `Obligations/Hash.lean` | HASH |
| `Obligations/Ser.lean` | SER |
| `Obligations/Size.lean` | SIZE |
| `Obligations/Store.lean` | STORE |
-/
